### ISSUE TITLE
license

### ISSUE THREAD

**Issue by larshp** [alwinvandeput/abap_bapi_bo_class_generator#5]
Suggest adding a license, see https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by alwinvandeput** [comment]
I saw that it was possible, but I preferred to have the license in the code, because the code can also be copied from one SAP system to another and then not all ABAP developers know the license. Do you see additional advantages of putting an extra license file in the GitHub repository?

**Comment by larshp** [comment]
it shows up in the upper right corner, if there is a license file
![image](https://user-images.githubusercontent.com/5888506/65222526-8ebefa00-dabf-11e9-8456-8bc2b157801b.png)
